name: Docker Build & Push

on:
  push:
    branches: [ main ]  # ou "master" si c’est ta branche principale

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write  # nécessaire pour pousser vers ghcr.io
      contents: read

    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Connexion à GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up environment variables
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> $GITHUB_ENV


      - name: Build de l'image Docker
        run: |
            repo_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            docker build -t ghcr.io/$repo_name:latest .
        
      - name: Push vers ghcr.io
        run: |
            repo_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            docker push ghcr.io/$repo_name:latest